# Main project parameters
#=====================================#

# Set the tracking system to be used for processing
tracker: cnn


# Data directories and parameters
#=====================================#

datadir: data/testVids
outputdir: data/output
templatedir: data/templates

boundPool: False
extract_data: True
load_pickle: False

savetoexcel: True
outputExcel: trackingData.xlsx

# Video processing parameters
#=====================================#

framerate: 30
alpha: 0.25
verbose: True


# Hyperparams for general cnn training
#=====================================#

yolo:
  batch_size: 128
  num_epochs: 200
  validation_every: 1

  weight_decay: 0.0005

  learning_rate_schedule:
      init: 0.1
      final: 0.0001

  momentum_schedule:
      0: 0.0
      1: 0.5
      2: 0.9

cnn:
  traindir: data/trainData
  img_size: 72

  validation_proportion: 0.1
  batch_size: 100
  num_epochs: 200

  learning_rate: 0.75

# Parameters for Particle filter
#=====================================#

pfilter:
  num_particles: 10000
  detector: template

# Parameters for OpenCV tracker
#=====================================#

opencv:
    algorithm: kcf  # defaults to kcf

# Parameters for simple image analysis approaches
#=====================================#

template:
  threshold: 0.5
  template_ccorr: 'cv2.TM_SQDIFF_NORMED'
  template_thresh: 0.8

canny:
  threshold1: 180
  threshold2: 360
  min_area: 300
  max_area: 800
  min_arc_length: 60
  max_arc_length: 180