# Main project parameters
#=====================================#

# Set the tracking system to be used for processing
tracker: pfilter


# Data directories and parameters
#=====================================#

datadir: data/testVids
outputdir: data/output
templatedir: data/templates
save_extract_images: True

getMouseParams: True
boundPool: True
boundLoc: True
# coordinates from previous pool bounding
minx: 380
maxx: 1000
miny: 140
maxy: 675

num_train_vids: 10
frame_skip: 4

savetoexcel: True
outputExcel: trackingData.xlsx
saveIDs: True


# Video processing parameters
#=====================================#

framerate: 30
alpha: 0.25
verbose: False
prev_bounds: 128


# Hyperparams for general cnn training
#=====================================#

yolo:
  img_size: 48

  optimizer: adam

  batch_size: 128
  num_epochs: 200
  validation_every: 1

  weight_decay: 0.0005

  learning_rate_schedule:
      init: 0.1
      final: 0.0001

  momentum_schedule:
      0: 0.0
      1: 0.5
      2: 0.9

cnn:
  train_model: True
  traindir: data/trainData
  training_verbose: False

  trainpickle: train_data.pickle
  testpickle: test_data.pickle

  early_stop: True
  early_stop_epochs: 15
  early_stop_verbose: 1

  dropout: 0.5

  augmentation: True

  img_size: 64

  resize: 1.0
  optimizer: adam

  validation_proportion: 0.25
  batch_size: 100
  num_epochs: 50
  seed: 13

  learning_rate: 0.75

  output_weights: custom_weights-smaller.hdf5
  fitted_weights: custom_weights-smaller.hdf5
  load_weights: True

  window_stride: 4


# Parameters for Particle filter
#=====================================#

pfilter:
  num_particles: 1000
  bound_size: 180
  detector: canny


# Parameters for OpenCV tracker
#=====================================#

opencv:
    algorithm: kcf  # defaults to kcf


# Parameters for simple image analysis approaches
#=====================================#

template:
  threshold: 0.5
  template_ccorr: 'cv2.TM_SQDIFF_NORMED'
  template_thresh: 0.8

canny:
  threshold1: 140
  threshold2: 280
  min_area: 140
  max_area: 1000
  min_arc_length: 20
  max_arc_length: 400

kalman:
  noise: 1.0
