# Main project parameters
#=====================================#

# Set the tracking system to be used for processing
tracker: opencv


# Data directories and parameters
#=====================================#

datadir: data/testVids
outputdir: data/output
templatedir: data/templates

# Video processing parameters
#=====================================#

framerate: 30
adaptive_alpha: 0.25

# Hyperparams for general cnn training
#=====================================#

yolo:
  batch_size: 128
  num_epochs: 200
  validation_every: 1

  weight_decay: 0.0005

  learning_rate_schedule:
      init: 0.1
      final: 0.0001

  momentum_schedule:
      0: 0.0
      1: 0.5
      2: 0.9

# Parameters for Particle filter
#=====================================#

pfilter:
  num_particles: 1000

# Parameters for OpenCV tracker
#=====================================#

opencv:
    algorithm: kcf  # defaults to kcf